### ISSUE TITLE
dependencies have capitalisation problems

### ISSUE THREAD

**Issue by rootsical** [jbmusso/tinkergraph-js#1]
i think on my system, the discrepancy in capitalisation of the required modules is causing problems, for example require('./TinkerVertex') instead of require('./tinkervertex'), resulting in a 'Cannot find module' error. hope this library continues - it's great!

**Comment by jbmusso** [comment]
This is true. I develop on Mac OS X where this does not matter. I'd have to be more careful and normalize all paths. I plan to rewrite this from scratch with ES2015/2016.
