### ISSUE TITLE
Compatible with TinkerPop3

### ISSUE THREAD

**Issue by phreed** [jbmusso/tinkergraph-js#3]
Is this ready for the browser?
Is it compatible with TinkerPop3?

**Comment by jbmusso** [comment]
It may be working in browsers, you may have some luck if you use browserify/webpack. Actually, this needs to be rewritten from scratch with ES2015/2016.
What do you mean by "compatible with TinkerPop3"?

**Comment by phreed** [comment]
I missed the line in your readme saying that this was written for tinkerpop3. my mistake.
